### ISSUE TITLE
Missing dependency File::Which in version 0.50

### ISSUE THREAD

**Issue by perlpunk** [sni/Monitoring-Generator-TestConfig#5]
`10-Test-Config-Creation.t` is using File::Which:
https://metacpan.org/source/NIERLEIN/Monitoring-Generator-TestConfig-0.50/t%2F10-Test-Config-Creation.t

but it is nowhere specified as a dependency.

Stumbled over this this while maintaining the openSUSE perl repository https://build.opensuse.org/package/show/devel:languages:perl/perl-Monitoring-Generator-TestConfig

**Comment by sni** [comment]
you are right, i updated the requirements.

**Comment by perlpunk** [comment]
That was fast, thanks :)

Are you planning a new release?

**Comment by sni** [comment]
its on the way to cpan. It might take a day or two till the mirrors are updated.

**Comment by sni** [comment]
Turns out, File::Which is not used at all anymore. Next release will not use or mention it anymore.
